### PR TITLE
Add scheduler

### PR DESCRIPTION
**Pull request by losfair**
The current task scheduler implemented in `spider.py` is dirty and requires fixes.

This pull request implements a scheduler in `sched.py`.

### CODE REVIEW

**Comment by Nugine** [comment]
Thanks for your contribution!
1. 我不认为现有的调度方式是"dirty"的，请指出具体何处"dirty"。
2. Spider的接口将在下一个commit中调整，从而导致调度方式的微调，敬请关注。
3. 根据奥卡姆剃刀原理，我仍打算使用闭包协程来完成调度，不增加多余的类。

**Comment by losfair** [comment]
The current implementation works just fine for small-sized web crawler projects.

However, the codebase isn't ready (yet) for long-term maintenance because of the lack of proper design.

Taking two of the design issues as examples:

1. Lack of abstraction: 
- works should be dispatched and executed in a properly abstracted model rather than nested functions
- a special interface like Handle could be provided to the actual executor for mutating the state of Spider objects. This hides implementation details to user code and therefore helps to achieve API stability. However, the current code makes use of return values to modify a partial state (node_queue) - defeating its own purpose.

2. Black magic: The current code does a lot of tricks to maintain consistency (first_works, tricky uses of asyncio.Lock, etc.) - It's just not how computers (or software systems) work.

**Comment by Nugine** [comment]
1. 定位如此，面向单机、个人、中小规模的爬虫，不考虑大规模爬取。
2. 我认为如果没有扩展性的要求，不需要增加实体。假如现有机制无法适应未来的需求（现在没考虑到的），那应在未来重构。
3. 将返回值（Node类型）添加到node_queue的设计取自Scrapy（yield Request(...)）.现已使用spider.insert_nodes()和spider.append_nodes()取代。
4.  asyncio.Lock应如何使用？

**Comment by Nugine** [comment]
first_works确实可以去掉，晚上改

**Comment by losfair** [comment]
It's up to you to make design decisions :D
You will understand once you've written more code.

**Pull request closed without merging**
